config/routes.rb
Rails.application.routes.draw do
	match '/track' => 'event_receiver#track', :via => [:get, :post]
	match '/profile' => 'profile_receiver#track', :via => [:get, :post]

	post '/track_event' => 'gerals#track_event'
	post '/track_profile' => 'gerals#track_profile'

	post '/events_of_app' => 'gerals#events_of_app'
	post '/properties_of_event' => 'gerals#properties_of_event'
	post '/profiles_of_app' => 'gerals#profiles_of_app'
	post '/profiles_properties' => 'gerals#profiles_properties'

	post '/profiles_report' => 'gerals#profile_report'
	post '/segmentation_report' => 'gerals#segmentation_report'
	post '/people_report' => 'gerals#people_report'
	post '/funnel_report' => 'gerals#funnel_report'
	post '/funnel_report_profiles_at_step' => 'gerals#funnel_report_profiles_at_step'

	root 'apps#index'
	resources :apps do
		get :events_form
		get :profiles_form
		get :profiles_report
		get :segmentation_report
		get :people_report
		get :funnel_report
	end
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <b>Nome</b><br>
    <%= f.text_field :name %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/events_form.html.erb
<div ng-app="dos" ng-controller="events_form">

	<b>Event type</b>
	<input type="text" ng-model="event.type" class="form-control">

	<br>
	<b>External Id</b>
	<select ng-options="p for p in profiles" ng-model="event.external_id" class="form-control"></select>

	<br>

	<b>Event properties</b>
	<div ng-repeat="property in properties">
		<div class="row">
			<div class="col-sm-6">
				<input type="text" ng-model="property.name" class="form-control">
			</div>
			<div class="col-sm-6">
				<input type="text" ng-model="property.value" class="form-control">
			</div>
		</div>
	</div>


	<br>
	<button class="btn btn-default" ng-click="addProperty()">Add Property</button>
	<button class="btn btn-primary" ng-click="track()">Track</button>
</div>

app/views/apps/funnel_report.html.erb
<div ng-app="dos" ng-controller="funnel_report">
	<div class="row">
		<div class="col-sm-3">
			<b>Etapas do funil</b>

			<br>
			<div ng-repeat="step in steps">
				<select ng-model="step.event" ng-options="e for e in events" class="form-control"></select>
			</div>

			<br>
			<button class="btn btn-primary" ng-click="addStep()">Adicionar etapa</button>

			<hr>
			<b>De</b>
			<input type="text" ng-model="time_range.from" class="form-control">
			<br>
			<b>Até</b>
			<input type="text" ng-model="time_range.to" class="form-control">
		</div>

		<div class="col-sm-9">
			<b>Filtros</b>
			<div class="row">
				<div ng-repeat="filter in filters">
					<div class="col-sm-4">
						<select ng-options="e for e in events" ng-model="filter.eventType" class="form-control"></select>
					</div>
					<div class="col-sm-4">
						<select ng-options="e for e in propertiesOfEvent(filter.eventType)" ng-model="filter.property" class="form-control"></select>
					</div>
					<div class="col-sm-4">
						<select ng-options="e for e in valuesOfProperty(filter.eventType, filter.property)" ng-model="filter.value" class="form-control"></select>
					</div>
				</div>
			</div>

			<br>
			<button class="btn btn-default" ng-click="addFilter()">Adicionar filtro</button>
			<button class="btn btn-primary" ng-click="render()">Gerar relatório</button>

			<hr>
			<div id="funnel-chart"></div>
			<hr>
		</div>
	</div>

	<hr>

	<div class="row">
		<div class="col-sm-3">
			<b>Perfis que chegaram até a etapa</b>
			<input type="text" ng-model="profilesAtStep" class="form-control">

			<br>
			<div ng-repeat="header in headers">
				<select ng-model="header.name" ng-options="p for p in propertiesOfProfiles" class="form-control"></select>
			</div>

			<br>
			<button class="btn btn-default btn-block" ng-click="addHeader()">Adicionar coluna</button>
			<button class="btn btn-primary btn-block" ng-click="renderPeople()">Gerar relatório</button>
		</div>

		<div class="col-sm-9">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>External Id</th>
						<th ng-repeat="header in headers">
							{{header.name}}
						</th>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="person in people">
						<td>{{person.external_id}}</td>
						<td ng-repeat="header in headers">
							{{person.properties[header.name]}}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= link_to 'Relatórios', app %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/people_report.html.erb
<div ng-app="dos" ng-controller="people_report">
	<div class="row">
		<div class="col-sm-12">
			<b>Filtros</b>
			<br>
			<div ng-repeat="filter in filters">
				<div class="row">
					<div class="col-sm-4">
						<select ng-model="filter.property" ng-options="p for p in properties" class="form-control"></select>
					</div>
					<div class="col-sm-3">
						<select ng-model="filter.operator" ng-options="o for o in operators" class="form-control"></select>
					</div>
					<div class="col-sm-5">
						<div ng-if="filter.operator == '='">
							<select ng-model="filter.value" ng-options="v for v in valuesOfProperty(filter.property)" class="form-control"></select>
						</div>
						<div ng-if="filter.operator != '='">
							<input type="text" ng-model="filter.value" class="form-control">
						</div>
					</div>
				</div>
			</div>

			<br>
			<button class="btn btn-default" ng-click="addFilter()">Adicionar filtro</button>
			<button class="btn btn-primary" ng-click="render()">Gerar relatório</button>
		</div>
	</div>

	<hr>
	<div class="row">
		<div class="col-sm-3">
			<div ng-repeat="header in headers">
				<select ng-model="header.name" ng-options="p for p in properties" class="form-control"></select>
			</div>

			<br>
			<button class="btn btn-default" ng-click="addHeader()">Adicionar coluna</button>
		</div>

		<div class="col-sm-9">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>External Id</th>
						<th ng-repeat="header in headers">
							{{header.name}}
						</th>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="person in people">
						<td>{{person.external_id}}</td>
						<td ng-repeat="header in headers">
							{{person.properties[header.name]}}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/apps/profiles_form.html.erb
<div ng-app="dos" ng-controller="profiles_form">

	<b>External Id</b>
	<input type="text" ng-model="profile.external_id" class="form-control">

	<br>

	<b>Profile properties</b>
	<div ng-repeat="property in properties">
		<div class="row">
			<div class="col-sm-6">
				<input type="text" ng-model="property.name" class="form-control">
			</div>
			<div class="col-sm-6">
				<input type="text" ng-model="property.value" class="form-control">
			</div>
		</div>
	</div>


	<br>
	<button class="btn btn-default" ng-click="addProperty()">Add Property</button>
	<button class="btn btn-primary" ng-click="track()">Track</button>
</div>

app/views/apps/profiles_report.html.erb
<div ng-app="dos" ng-controller="profiles_report">
	<div class="row">
		<div class="col-sm-6">
			<b>Perfil sendo comparado</b>
			<select ng-options="p for p in profiles" ng-model="externalId" class="form-control"></select>
			
			<br>
			<b>De</b>
			<input type="text" ng-model="time_range.from" class="form-control">
			<br>
			<b>Até</b>
			<input type="text" ng-model="time_range.to" class="form-control">
		</div>

		<div class="col-sm-6">
			<b>Eventos</b>
			<div ng-repeat="e in eventsToCompare">
				<select ng-options="e for e in events" ng-model="e.eventType" class="form-control"></select>
			</div>

			<br>
			<button class="btn btn-default" ng-click="addEvent()">Adicionar evento</button>
		</div>
	</div>

	<br>
	<b>Filtros</b>
	<div class="row">
		<div ng-repeat="filter in filters">
			<div class="col-sm-4">
				<select ng-options="e for e in events" ng-model="filter.eventType" class="form-control"></select>
			</div>
			<div class="col-sm-4">
				<select ng-options="e for e in propertiesOfEvent(filter.eventType)" ng-model="filter.property" class="form-control"></select>
			</div>
			<div class="col-sm-4">
				<select ng-options="e for e in valuesOfProperty(filter.eventType, filter.property)" ng-model="filter.value" class="form-control"></select>
			</div>
		</div>
	</div>

	<br>
	<div class="row">
		<div class="col-sm-12">
			<button class="btn btn-default" ng-click="addFilter()">Adicionar filtro</button>
			<button class="btn btn-primary" ng-click="render()">Gerar relatório</button>
		</div>
	</div>

	<br>
	<div class="row">
		<div class="col-sm-6">
			<div id="chart-profile" style="border: 1px solid #DFDFDF;"></div>
		</div>
		<div class="col-sm-6">
			<div id="chart-average" style="border: 1px solid #DFDFDF;"></div>
		</div>
	</div>
</div>

app/views/apps/segmentation_report.html.erb
<div ng-app="dos" ng-controller="segmentation_report">
	<div class="row">
		<div class="col-sm-3">
			<b>Evento</b>
			<select ng-options="e for e in events" ng-model="eventType" class="form-control"></select>

			<br>
			<b>De</b>
			<input type="text" ng-model="time_range.from" class="form-control">
			<br>
			<b>Até</b>
			<input type="text" ng-model="time_range.to" class="form-control">

			<br>
			<b>Propriedade para segmentar</b>
			<select ng-options="e for e in propertiesOfEvent(eventType)" ng-model="segmentBy" class="form-control"></select>

			<br>
			<button class="btn btn-primary" ng-click="render()">Segmentar</button>

			<hr>

			<div ng-repeat="header in headers">
				<select ng-options="e for e in propertiesOfEvent(eventType)" ng-model="header.property" class="form-control"></select>
			</div>

			<br>
			<button class="btn btn-default" ng-click="addHeader()">Adicionar coluna</button>
		</div>

		<div class="col-sm-9">
			<div id="chart-segmentation"></div>

			<hr>

			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>{{segmentBy}}</th>
						<th ng-repeat="header in headers">
							{{header.property}}
						</th>
						<th>Momento</th>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="event in reportEvents">
						<td>{{event.properties[segmentBy] || '--'}}</td>
						<td ng-repeat="header in headers">
							{{event.properties[header.property] || '--'}}
						</td>
						<td>{{event.happened_at | dateFilter}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>