config/routes.rb
Rails.application.routes.draw do
	match '/track' => 'event_receiver#track', :via => [:get, :post]
	match '/profile' => 'profile_receiver#track', :via => [:get, :post]

	post '/track_event' => 'gerals#track_event'
	post '/track_profile' => 'gerals#track_profile'

	post '/events_of_app' => 'gerals#events_of_app'
	post '/properties_of_event' => 'gerals#properties_of_event'
	post '/profiles_of_app' => 'gerals#profiles_of_app'
	post '/profiles_properties' => 'gerals#profiles_properties'

	post '/profiles_report' => 'gerals#profile_report'
	post '/segmentation_report' => 'gerals#segmentation_report'
	post '/people_report' => 'gerals#people_report'
	post '/funnel_report' => 'gerals#funnel_report'
	post '/funnel_report_profiles_at_step' => 'gerals#funnel_report_profiles_at_step'

	root 'apps#index'
	resources :apps do
		get :events_form
		get :profiles_form
		get :profiles_report
		get :segmentation_report
		get :people_report
		get :funnel_report
	end
end

app/views/layouts/app_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Analytics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">DOS</small></a>
			</div>

			<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="dropdown">
			            <a href="/">
			            	Aplicações
			            </a>
			        </li>
				</ul>
			</div>
		</div>
	</nav>

	<script type="text/javascript">
		window.app = <%= raw(@app.to_json.to_s.gsub('nil', 'null')) %>;
	</script>

	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<div style="border: 1px solid #DFDFDF; border-bottom: none; height: 40px; line-height: 40px; background-color: #FAFAFA; padding: 0 15px;">
					Aplicação: <b><%= @app.name %></b>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-3">
				<ul class="list-group">
					<li class="list-group-item">
						<%= link_to 'Relatório de Perfil', app_profiles_report_path(@app) %>
					</li>

					<li class="list-group-item">
						<%= link_to 'Relatório de Segmentação', app_segmentation_report_path(@app) %>
					</li>

					<li class="list-group-item">
						<%= link_to 'Relatório de Pessoas', app_people_report_path(@app) %>
					</li>

					<li class="list-group-item">
						<%= link_to 'Relatório de Funil', app_funnel_report_path(@app) %>
					</li>

					<li class="list-group-item">
						--
					</li>

					<li class="list-group-item">
						<%= link_to 'Formulário de eventos', app_events_form_path(@app) %>
					</li>

					<li class="list-group-item">
						<%= link_to 'Formulário de perfis', app_profiles_form_path(@app) %>
					</li>
				</ul>
			</div>

			<div class="col-sm-9" >
				<div style="background-color: #FFF; padding: 10px; border: 1px solid #DFDFDF;">
					<%= yield %>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Analytics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">DOS</small></a>
			</div>

			<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="dropdown">
			            <a href="/">
			            	Aplicações
			            </a>
			        </li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>